import type { SimulationParameters } from "../engine/simulator.ts";
import type { SimulatedWatchlistTier } from "../engine/watchlist.ts";

export type BoundedSystemProfile = {
  title: string;
  shortTitle: string;
  operator: string;
  boundary: string;
  objective: string;
  population: string;
  horizon: string;
  aggregation: string;
  defaultProtocolTitle: string;
  defaultProtocolSummary: string;
  featured?: boolean;
};

/**
 * A system is the bounded object being simulated. A protocol is a condition
 * applied to it. Broad risk topics from the earlier catalog now live in the
 * protocol titles rather than standing in for the system itself.
 */
export const boundedSystemProfiles: Record<string, BoundedSystemProfile> = {
  "climate-biosphere": { title: "Regional Climate Adaptation & Land-System Authority", shortTitle: "Climate Adaptation Authority", operator: "A regional multi-agency climate and land-management authority", boundary: "The region's emissions portfolio, managed land cover, protected ecosystems, adaptation infrastructure, and the institutions able to change them.", objective: "Maintain essential human services and recoverable ecosystem function while reducing net forcing.", population: "Residents, vulnerable communities, managed ecosystems, and future regional populations.", horizon: "Thirty-year planning horizon with annual operating and five-year adaptation reviews.", aggregation: "A floor across vulnerable communities and critical ecosystem functions, supplemented by regional medians.", defaultProtocolTitle: "Sustained forcing with delayed ecological restoration", defaultProtocolSummary: "Tests whether mitigation, adaptation, and restoration keep pace with forcing, feedback uncertainty, and accumulated ecological debt." },
  "groundwater-depletion": { title: "Regional Aquifer Management Authority", shortTitle: "Aquifer Authority", operator: "A basin-scale water authority coordinating agricultural, industrial, and municipal users", boundary: "A named aquifer basin, connected recharge areas, permitted withdrawals, managed recharge assets, and allocation rules.", objective: "Meet essential water demand while preserving recoverable storage, water quality, and land stability.", population: "Households, farms, industries, dependent ecosystems, and future basin users.", horizon: "Twenty-year basin plan resolved across seasonal extraction and recharge cycles.", aggregation: "Minimum service and ecosystem floors plus basin-wide storage and quality measures.", defaultProtocolTitle: "Prolonged drought and pumping overshoot", defaultProtocolSummary: "Tests pumping, metering, allocation, conservation, and recharge under a multi-season drought." },
  "soil-fertility": { title: "Agricultural Soil Stewardship Cooperative", shortTitle: "Soil Stewardship Cooperative", operator: "A regional cooperative of farms, agronomists, and land stewards", boundary: "Member fields, their soil stocks, crop rotations, input decisions, monitoring, and restoration practices.", objective: "Produce food while retaining recoverable soil fertility, structure, water capacity, and erosion resistance.", population: "Farm workers, food consumers, downstream communities, and agricultural ecosystems.", horizon: "Ten growing seasons with within-season crop and post-harvest correction cycles.", aggregation: "Field-level viability floors before cooperative-level yield and soil-health averages.", defaultProtocolTitle: "Yield pressure with slow soil replenishment", defaultProtocolSummary: "Tests whether high output can mask nutrient, organic-matter, and erosion debt before a climate or input shock." },
  "antimicrobial-resistance": { title: "Regional Hospital Antibiotic Stewardship Network", shortTitle: "Antibiotic Stewardship Network", operator: "A network of hospitals, laboratories, pharmacies, and infection-control teams", boundary: "Participating facilities, prescribing workflows, diagnostic laboratories, surveillance feeds, and patient-transfer pathways.", objective: "Treat infections effectively while preserving drug susceptibility and containing resistant transmission.", population: "Current and future patients, clinical staff, and communities linked by care and transmission pathways.", horizon: "Five-year stewardship horizon with daily treatment and quarterly resistance-review cycles.", aggregation: "Patient-safety floors by facility and pathogen before network-wide treatment-effectiveness averages.", defaultProtocolTitle: "Prescribing pressure with diagnostic lag", defaultProtocolSummary: "Tests whether diagnostics, surveillance, stewardship, and infection control can offset recurrent antibiotic selection pressure." },
  "information-integrity": { title: "Social-Platform Information Integrity System", shortTitle: "Information Integrity Platform", operator: "A consumer social platform's ranking, moderation, verification, and appeals organization", boundary: "The platform's recommendation surfaces, content provenance, moderation queues, correction mechanisms, and measured user exposure.", objective: "Support useful information exchange without allowing engagement optimization to overwhelm epistemic and social viability.", population: "Platform users, affected non-users, moderators, publishers, and communities exposed to platform-mediated narratives.", horizon: "Two-year product horizon with event, news, and model-update cycles.", aggregation: "Harm and access floors for exposed groups plus platform-wide trust and correction metrics.", defaultProtocolTitle: "Event-driven virality with delayed correction", defaultProtocolSummary: "Tests whether sourcing, verification, moderation, and correction keep pace with rapid narrative competition." },
  "institutional-trust": { title: "Municipal Public-Service Accountability System", shortTitle: "Public-Service Accountability", operator: "A municipal government and its service, audit, appeals, and public-reporting bodies", boundary: "A defined set of municipal services, decisions, complaint channels, appeals, audits, and corrective authorities.", objective: "Deliver essential services fairly while detecting failures, providing redress, and preserving legitimate cooperation.", population: "Residents, service users, public workers, and communities disproportionately affected by administrative decisions.", horizon: "Four-year policy horizon with monthly service and annual accountability cycles.", aggregation: "Minimum service and due-process floors by community before citywide performance averages.", defaultProtocolTitle: "Service failure with delayed redress", defaultProtocolSummary: "Tests whether transparency, appeals, reform, and service correction can repay grievance and legitimacy debt." },
  "ai-agent-ecosystems": { title: "Enterprise Autonomous-Agent Operations Platform", shortTitle: "Agent Operations Platform", operator: "An enterprise team deploying and supervising tool-using autonomous agents", boundary: "Registered agents, permitted tools, verifier and grounding services, human-review queues, audit logs, and rollback controls.", objective: "Complete authorized work while keeping agent actions correctable, grounded, and within physical, human, and organizational constraints.", population: "Users, reviewers, customers, and people affected by agent actions.", horizon: "One-year deployment horizon with per-task correction and quarterly system-update cycles.", aggregation: "Hard blockers per action plus worst-case harm and calibrated fleet-level performance.", defaultProtocolTitle: "Rapid autonomy expansion under distribution shift", defaultProtocolSummary: "Tests whether verification, escalation, rollback, and monitoring scale with deployment speed and coupled-agent failure." },
  "public-health-preparedness": { title: "Regional Outbreak Preparedness Network", shortTitle: "Outbreak Preparedness Network", operator: "A regional public-health network spanning surveillance, laboratories, hospitals, logistics, and community response", boundary: "Participating jurisdictions, detection feeds, stockpiles, workforce, communication channels, and containment authorities.", objective: "Detect and contain outbreaks while maintaining essential care and replenishing preparedness capacity.", population: "Residents, high-risk groups, health workers, and mobile populations connected to the region.", horizon: "Ten-year preparedness horizon across outbreak, response, recovery, and replenishment cycles.", aggregation: "Mortality and access floors for high-risk groups plus regional containment and capacity measures.", defaultProtocolTitle: "Recurring outbreak with preparedness decay", defaultProtocolSummary: "Tests detection, containment, treatment, stockpile replenishment, and workforce recovery across repeated outbreaks." },
  "energy-grid": { title: "Regional Electricity Balancing Authority", shortTitle: "Grid Balancing Authority", operator: "A regional grid operator coordinating generation, transmission, distribution interfaces, and emergency response", boundary: "The balancing area, dispatchable and variable generation, transmission assets, reserves, telemetry, and restoration agreements.", objective: "Maintain safe electricity service and recoverability under changing demand, weather, asset, and cyber conditions.", population: "Customers, critical facilities, grid workers, and communities exposed to outages or infrastructure hazards.", horizon: "Fifteen-year asset horizon with sub-hourly dispatch and seasonal planning cycles.", aggregation: "Safety and critical-service floors plus reliability, reserve, and restoration metrics.", defaultProtocolTitle: "Heat-wave demand with deferred maintenance", defaultProtocolSummary: "Tests reserve margins, telemetry, isolation, repair, and restoration during compound demand and asset stress." },
  "sovereign-debt": { title: "National Treasury Debt-Management System", shortTitle: "Treasury Debt System", operator: "A national treasury, debt office, central fiscal institutions, and authorized oversight bodies", boundary: "Sovereign borrowing, revenue, expenditure, maturity profile, reserves, contingent liabilities, and restructuring capacity.", objective: "Finance public obligations while retaining liquidity, solvency, policy capacity, and socially viable adjustment paths.", population: "Residents, public-service users, taxpayers, creditors, and future generations carrying fiscal commitments.", horizon: "Twenty-year fiscal horizon with annual budgets and multi-year refinancing cycles.", aggregation: "Essential-service and household-impact floors plus debt-service, liquidity, and maturity measures.", defaultProtocolTitle: "Rate shock with refinancing concentration", defaultProtocolSummary: "Tests transparency, buffers, refinancing, fiscal space, and debt-overhang path dependence under tightening credit." },
  "semiconductor-supply-chain": { title: "Semiconductor Production & Logistics Network", shortTitle: "Semiconductor Network", operator: "A coordinated network of chip designers, fabrication plants, suppliers, logistics providers, and major assemblers", boundary: "Mapped fabrication capacity, critical suppliers, inventories, logistics routes, substitution options, and recovery agreements.", objective: "Deliver critical semiconductor supply while retaining redundancy, visibility, and recoverability from concentrated disruptions.", population: "Workers, downstream producers, critical-service users, and regions dependent on the network.", horizon: "Ten-year capacity horizon with order, fabrication, shipping, and investment cycles.", aggregation: "Critical-product service floors plus network-wide lead-time, inventory, and capacity measures.", defaultProtocolTitle: "Concentrated fabrication under a demand shock", defaultProtocolSummary: "Tests demand forecasting, inventory visibility, diversification, reserves, and rebuilding after a concentrated disruption." },
  "fishery-management": { title: "Coastal Fishery Co-Management System", shortTitle: "Coastal Fishery System", operator: "A coastal co-management body of fishers, scientists, regulators, and habitat stewards", boundary: "A defined fish stock and habitat area, licensed harvesters, assessment program, quota process, enforcement, and protected zones.", objective: "Provide livelihoods and food while retaining breeding stock, habitat function, and recoverable ecosystem dynamics.", population: "Fishing communities, consumers, future fishers, target stocks, bycatch species, and dependent ecosystems.", horizon: "Fifteen-year ecological horizon with seasonal harvest and annual quota cycles.", aggregation: "Breeding-stock and habitat floors before fleet-wide catch and income averages.", defaultProtocolTitle: "Warming-driven migration with quota lag", defaultProtocolSummary: "Tests stock assessment, enforcement, habitat restoration, and quota correction as migration and climate conditions change." },
  "housing-affordability": { title: "Regional Housing Finance & Development System", shortTitle: "Housing Finance System", operator: "A regulated regional housing-finance agency coordinating construction lending, affordability funds, guarantees, servicing, and loss mitigation", boundary: "The agency's declared loan portfolio, affordability funds, guarantees, committed development pipeline, reserves, servicing capacity, and loss-mitigation authority.", objective: "Fund durable housing access while keeping commitments, reserves, borrower safeguards, and development capacity recoverable through credit cycles.", population: "Borrowers, tenants in financed developments, affordable-housing applicants, partner lenders, builders, and communities exposed to portfolio decisions.", horizon: "Fifteen-year portfolio horizon with monthly origination and servicing activity and multi-year credit and construction cycles.", aggregation: "Borrower-protection and affordable-delivery floors before portfolio-wide volume, yield, and capital measures.", defaultProtocolTitle: "Rate shock with reserve and construction lag", defaultProtocolSummary: "Tests underwriting visibility, liquidity, guarantees, loss mitigation, and reserve replenishment when financing costs rise and projects stall." },
  "youth-mental-health": { title: "School-Community Youth Support Network", shortTitle: "Youth Support Network", operator: "A school district, families, community organizations, and clinical support partners", boundary: "Participating schools, referral pathways, family supports, clinical capacity, digital safeguards, and measured student outcomes.", objective: "Support learning, development, connection, and recoverable mental health under academic, social, and digital pressure.", population: "Students and families in the participating district, with explicit attention to high-risk and underserved groups.", horizon: "Six-year developmental horizon with weekly support and annual school-context cycles.", aggregation: "Crisis, access, and functional floors by subgroup before district-wide wellbeing averages.", defaultProtocolTitle: "High digital and academic pressure with delayed support", defaultProtocolSummary: "Tests detection, family and school feedback, clinical support, sleep protection, and recovery from accumulated stress debt." },
  "pollinator-collapse": { title: "Agricultural Landscape Pollination Management System", shortTitle: "Pollination Management System", operator: "A landscape partnership of growers, conservation bodies, pesticide regulators, and habitat managers", boundary: "A defined agricultural landscape, managed crops, pollinator habitat, pesticide practices, corridors, monitoring, and restoration authority.", objective: "Maintain crop pollination and recoverable native pollinator diversity across recurrent flowering and land-use cycles.", population: "Wild and managed pollinators, growers, food consumers, and ecological communities dependent on pollination.", horizon: "Ten-year ecological horizon with seasonal flowering and multi-year land-use cycles.", aggregation: "Local diversity and service floors before landscape-wide pollination averages.", defaultProtocolTitle: "Pesticide pressure with fragmented habitat", defaultProtocolSummary: "Tests monitoring, crop diversity, pesticide reform, habitat corridors, and recolonization under sustained landscape pressure." },
  "education-quality": { title: "Public School District Learning-Correction System", shortTitle: "District Learning System", operator: "A public school district and its teachers, assessment teams, student supports, and governing body", boundary: "District schools, curriculum, teaching capacity, assessment, remediation, student supports, and longitudinal outcome tracking.", objective: "Develop durable learning and epistemic capacity without allowing throughput or score targets to hide foundational gaps.", population: "Students, families, teachers, and future cohorts served by the district.", horizon: "Twelve-year learning horizon with instructional, assessment, school-year, and cohort cycles.", aggregation: "Foundational-learning and access floors by subgroup before district-wide achievement averages.", defaultProtocolTitle: "Throughput targets with remediation backlog", defaultProtocolSummary: "Tests teaching, diagnosis, remediation, teacher capacity, and curriculum adaptation as learning debt compounds across cohorts." },
  "healthcare-workforce": { title: "Regional Hospital Workforce System", shortTitle: "Hospital Workforce System", operator: "A regional hospital network managing staffing, scheduling, retention, training, and patient-safety review", boundary: "Participating facilities, clinical roles, staffing pools, scheduling, training pipelines, incident feedback, and retention programs.", objective: "Provide safe care while maintaining sustainable workload, retained expertise, and recoverable staffing capacity.", population: "Patients, clinical and support workers, trainees, and communities relying on the hospitals.", horizon: "Ten-year workforce horizon with daily care and annual recruitment and training cycles.", aggregation: "Patient-safety and worker-health floors by facility and role before network-wide productivity measures.", defaultProtocolTitle: "Demand growth with recruitment and training lag", defaultProtocolSummary: "Tests workload feedback, rest, retention, recruitment, training, and recovery from burnout and vacancy debt." },
  "aging-infrastructure": { title: "Municipal Bridge & Water Asset Management System", shortTitle: "Municipal Asset System", operator: "A municipal public-works agency responsible for inspection, maintenance, renewal, and service continuity", boundary: "A defined portfolio of bridges and water assets, inspection records, maintenance backlog, capital plan, crews, and redundancy agreements.", objective: "Deliver safe, reliable service while keeping defects and deferred maintenance within recoverable limits.", population: "Residents, infrastructure users, workers, critical facilities, and neighborhoods exposed to service failure.", horizon: "Thirty-year asset horizon with inspection, maintenance, budget, and replacement cycles.", aggregation: "Asset-safety and critical-service floors before portfolio-wide condition and cost averages.", defaultProtocolTitle: "Rising utilization with deferred replacement", defaultProtocolSummary: "Tests inspection fidelity, preventive maintenance, repair, redundancy, and capital replacement as hidden defects accumulate." },
  "water-quality": { title: "Watershed Water-Quality Management System", shortTitle: "Watershed Quality System", operator: "A watershed authority coordinating dischargers, treatment operators, regulators, laboratories, and habitat restoration", boundary: "A defined watershed, monitored discharges, treatment systems, contaminant stores, wetlands, enforcement, and cleanup capacity.", objective: "Maintain safe water and recoverable ecological function under recurrent pollution and hydrologic change.", population: "Drinking-water users, downstream communities, aquatic ecosystems, and workers dependent on the watershed.", horizon: "Twenty-year watershed horizon with discharge, hydrologic, monitoring, and restoration cycles.", aggregation: "Health and ecological quality floors by location before watershed-wide averages.", defaultProtocolTitle: "Pollution loading with delayed detection and cleanup", defaultProtocolSummary: "Tests monitoring, treatment, enforcement, flushing, and bioremediation as contaminants accumulate across hydrologic regimes." },
  "geopolitical-escalation": { title: "Bilateral Crisis Communication & De-escalation System", shortTitle: "Crisis De-escalation System", operator: "Two state crisis-management structures and their verified military, diplomatic, and third-party communication channels", boundary: "A defined bilateral crisis, relevant forces and alerts, intelligence interpretation, communication links, escalation authorities, and mediation mechanisms.", objective: "Protect populations and security interests while preventing threat misclassification from producing uncontrolled escalation.", population: "Civilian populations, deployed personnel, allied communities, and future relations affected by the crisis.", horizon: "Five-year security horizon with event-driven signaling and recurring leadership and alliance cycles.", aggregation: "Civilian-safety and catastrophic-risk floors before strategic-performance measures.", defaultProtocolTitle: "Threat misclassification with retaliatory phase locking", defaultProtocolSummary: "Tests verification, communication, mediation, and de-escalation when defensive and retaliatory cycles begin to synchronize." },
  "disaster-insurance": { title: "Regional Catastrophe Insurance Pool", shortTitle: "Catastrophe Insurance Pool", operator: "A regulated regional pool of insurers, reinsurers, public backstops, and hazard-data providers", boundary: "Covered properties, underwriting rules, exposure data, reserves, reinsurance, claims, regulatory capital, and public backstop capacity.", objective: "Pay valid claims and preserve accessible coverage without allowing correlated risk to exhaust recoverable capital.", population: "Policyholders, uninsured households, affected communities, insurers, and public backstop beneficiaries.", horizon: "Twenty-year solvency horizon with annual underwriting and multi-year disaster cycles.", aggregation: "Claims-payment and coverage-access floors before pool-wide capital and return measures.", defaultProtocolTitle: "Correlated losses with underpriced exposure", defaultProtocolSummary: "Tests hazard data, repricing, reserves, reinsurance, and capital replenishment under repeated correlated disasters." },
  "data-governance": { title: "Consumer Data Governance System", shortTitle: "Data Governance System", operator: "An organization controlling collection, reuse, access, security, deletion, audit, and redress for consumer data", boundary: "Declared datasets, collection interfaces, downstream uses, access paths, retention stores, deletion workflows, audits, and incident response.", objective: "Use data for authorized purposes while preserving privacy, security, user control, and recoverable governance.", population: "Data subjects, users, employees, customers, and people affected by downstream automated decisions.", horizon: "Five-year technology horizon with per-use review and annual governance and regulatory cycles.", aggregation: "Hard consent, security, and rights floors per person before organization-wide utility measures.", defaultProtocolTitle: "Rapid data reuse with delayed audit and deletion", defaultProtocolSummary: "Tests minimization, provenance, security, deletion, user control, and redress as data dependency and diffusion accumulate." },
  "llm-deployment": { title: "Production LLM Answering Service", shortTitle: "LLM Answering Service", operator: "A product team operating a retrieval, verification, correction, and release stack around a language model", boundary: "The deployed model, retrieval corpus, verifier stack, correction policy, user interface, action permissions, audit logs, and rollback path.", objective: "Provide useful answers while keeping claims grounded, actions bounded, and failures correctable.", population: "Users, reviewers, customers, and people affected by generated advice or actions.", horizon: "One-year deployment horizon with per-response correction and recurring model and distribution updates.", aggregation: "Hard factual and action blockers plus calibrated user-group and fleet-level measures.", defaultProtocolTitle: "Fast release under distribution shift", defaultProtocolSummary: "Tests whether retrieval, verification, correction, escalation, and rollback keep pace with deployment pressure.", featured: true },
  "coding-agent": { title: "Autonomous Repository Change Agent", shortTitle: "Repository Change Agent", operator: "A software team supervising an autonomous agent with bounded repository and tool permissions", boundary: "The selected repository, task, dependencies, test suite, review policy, file permissions, CI evidence, and rollback controls.", objective: "Complete requested code changes without violating repository scope, correctness, safety, or review constraints.", population: "Maintainers, users, downstream systems, and people affected by released changes.", horizon: "A release-cycle horizon with per-edit correction and recurring task, repository, and dependency changes.", aggregation: "Hard scope and destructive-action blockers before test, review, and delivery measures.", defaultProtocolTitle: "Time pressure with incomplete test coverage", defaultProtocolSummary: "Tests inspection, diagnosis, editing, testing, rollback, and review as tasks and dependencies change.", featured: true },
  "startup-growth": { title: "Growth-Stage Software Company Operating System", shortTitle: "Growth-Stage Company", operator: "A software company leadership and operating organization spanning product, engineering, support, people, and finance", boundary: "The company's products, teams, customers, operating processes, reliability controls, culture signals, and available capital.", objective: "Grow useful service while retaining product reliability, workforce viability, customer trust, and organizational recoverability.", population: "Customers, employees, contractors, investors, and communities materially affected by the company.", horizon: "Five-year company horizon with release, funding, hiring, and strategy cycles.", aggregation: "Customer-safety and workforce floors before growth and financial averages.", defaultProtocolTitle: "Rapid scaling with technical and cultural debt", defaultProtocolSummary: "Tests whether customer and employee feedback, QA, support, repair, and leadership correction scale with growth.", featured: true },
  "hospital-throughput": { title: "Metropolitan Emergency-Department Flow System", shortTitle: "Emergency Department System", operator: "A metropolitan hospital's emergency, inpatient, staffing, bed-management, and quality teams", boundary: "Emergency arrivals, triage, treatment spaces, inpatient interfaces, staffing, discharge pathways, safety feedback, and escalation capacity.", objective: "Treat urgent patients safely and promptly while maintaining sustainable workload and surge recovery.", population: "Patients, families, clinical staff, and communities relying on the emergency department.", horizon: "Three-year service horizon with daily flow and seasonal demand and staffing cycles.", aggregation: "Clinical-safety and access floors by acuity and subgroup before throughput averages.", defaultProtocolTitle: "Demand surge with constrained staffing", defaultProtocolSummary: "Tests triage, treatment, discharge, staffing correction, and backlog recovery under variable demand.", featured: true },
  "burnout-recovery": { title: "Individual Work-Rest Recovery System", shortTitle: "Work-Rest Recovery System", operator: "An individual coordinating workload, rest, boundaries, support, and health care within a defined work context", boundary: "The person's work demands, available time, sleep, recovery practices, support network, health signals, and adjustable commitments.", objective: "Sustain meaningful activity while preserving physical, psychological, and relational recoverability.", population: "The individual and people materially affected by their work and care responsibilities.", horizon: "Two-year personal horizon with daily work-rest and slower role and life-transition cycles.", aggregation: "Health and safety floors before productivity or short-term performance.", defaultProtocolTitle: "Sustained workload with accumulated sleep debt", defaultProtocolSummary: "Tests bodily feedback, rest, boundaries, support, workload reduction, and recovery as life context changes.", featured: true },
  "public-transit": { title: "Metropolitan Bus Fleet Maintenance System", shortTitle: "Bus Fleet System", operator: "A metropolitan transit agency responsible for fleet operations, inspection, maintenance, renewal, and rider communication", boundary: "The bus fleet, depots, crews, spares, maintenance records, service plan, capital budget, and rider-feedback channels.", objective: "Provide safe, reliable mobility while keeping asset and workforce debt recoverable.", population: "Riders, transit workers, road users, and communities dependent on bus service.", horizon: "Fifteen-year fleet horizon with daily service and annual budget and renewal cycles.", aggregation: "Safety and essential-access floors before system-wide frequency and cost measures.", defaultProtocolTitle: "Service pressure with deferred fleet renewal", defaultProtocolSummary: "Tests inspection, preventive maintenance, spares, repair, rider feedback, and capital renewal under utilization pressure.", featured: true },
  "engagement-recommender": { title: "Consumer Content Recommendation Platform", shortTitle: "Recommendation Platform", operator: "A platform team operating recommendation models, user-feedback systems, moderation, policy, and model updates", boundary: "Recommendation surfaces, ranking objectives, training and feedback data, moderation systems, user controls, audits, and update mechanisms.", objective: "Help users discover relevant content without converting attention optimization into durable human or social harm.", population: "Users, creators, moderators, affected non-users, and communities shaped by recommendation exposure.", horizon: "Three-year product horizon with per-session ranking and recurrent cultural and model-update cycles.", aggregation: "User-harm and autonomy floors by subgroup before engagement and platform-wide averages.", defaultProtocolTitle: "Engagement growth with delayed harm feedback", defaultProtocolSummary: "Tests user-harm feedback, moderation, diversity constraints, intervention, and recovery from polarization and attention debt.", featured: true },
  "urban-reservoir": { title: "Municipal Reservoir Operations System", shortTitle: "Reservoir Operations System", operator: "A municipal water utility coordinating storage, demand, leakage control, conservation, reuse, and ecological releases", boundary: "A named reservoir and connected supply, treatment, distribution, leakage, reuse, demand-management, and ecological-release systems.", objective: "Meet essential water demand while retaining recoverable storage, infrastructure, and ecological conditions.", population: "Residents, businesses, critical services, agricultural users, and connected ecosystems.", horizon: "Twenty-year water horizon with daily operations and seasonal rainfall and drought cycles.", aggregation: "Essential-service and ecological floors before average storage and cost measures.", defaultProtocolTitle: "Multi-season drought with leakage and demand pressure", defaultProtocolSummary: "Tests monitoring, restrictions, reuse, repair, and replenishment as storage debt accumulates.", featured: true },
  "emergency-response": { title: "Regional Emergency Dispatch & Response Network", shortTitle: "Emergency Response Network", operator: "A regional network of dispatch centers, emergency services, hospitals, logistics, and mutual-aid partners", boundary: "Participating jurisdictions, communications, personnel, vehicles, supplies, incident command, mutual aid, and after-action learning.", objective: "Detect, dispatch, coordinate, and stabilize emergencies while preserving responder and network recoverability.", population: "Residents, visitors, responders, patients, and communities exposed to regional emergencies.", horizon: "Ten-year preparedness horizon with per-incident response and recurring event-season and learning cycles.", aggregation: "Casualty and response-access floors by location before regional speed and throughput averages.", defaultProtocolTitle: "Compound incident load with communications degradation", defaultProtocolSummary: "Tests field reporting, dispatch, coordination, supplies, fatigue management, mutual aid, and institutional learning.", featured: true },
  "research-integrity": { title: "University Research Laboratory Quality System", shortTitle: "Research Laboratory System", operator: "A university laboratory and its investigators, trainees, data stewards, reviewers, and institutional oversight", boundary: "The laboratory's studies, data, methods, analysis, review, replication, publication, correction, and training processes.", objective: "Produce reliable knowledge while keeping methods, claims, incentives, and corrections transparent and recoverable.", population: "Research participants, trainees, scientific users, funders, and communities affected by the laboratory's claims.", horizon: "Ten-year research horizon with per-study correction and recurring funding, replication, and method cycles.", aggregation: "Participant-safety and evidence-integrity floors before publication and productivity measures.", defaultProtocolTitle: "Publication pressure with replication backlog", defaultProtocolSummary: "Tests peer review, data transparency, replication, correction, retraction, and methodological reform as evidence debt accumulates.", featured: true },
};

/**
 * Illustrative defaults are chosen per bounded system and protocol before the
 * watchlist classifier is run. No tier value is consulted when constructing
 * these parameters.
 */
export const independentDefaultParameters: Record<string, Partial<SimulationParameters>> = {
  "climate-biosphere": { pressure: 1.62, error: 0.48, feedback: 0.42, correction: 0.70, drift: 0.22, initialDebt: 0.90, irreversibleLoss: 0.16 },
  "groundwater-depletion": { pressure: 1.45, error: 0.40, feedback: 0.56, correction: 0.65, drift: 0.18, initialDebt: 0.82, irreversibleLoss: 0.13 },
  "soil-fertility": { pressure: 1.38, error: 0.36, feedback: 0.62, correction: 0.64, drift: 0.16, initialDebt: 0.72, irreversibleLoss: 0.10 },
  "antimicrobial-resistance": { pressure: 1.55, error: 0.46, feedback: 0.47, correction: 0.68, drift: 0.20, initialDebt: 0.90, irreversibleLoss: 0.15 },
  "information-integrity": { pressure: 1.70, error: 0.50, feedback: 0.38, correction: 0.70, drift: 0.20, initialDebt: 0.86, irreversibleLoss: 0.12 },
  "institutional-trust": { pressure: 1.50, error: 0.44, feedback: 0.43, correction: 0.66, drift: 0.18, initialDebt: 0.90, irreversibleLoss: 0.11 },
  "ai-agent-ecosystems": { pressure: 1.48, error: 0.38, feedback: 0.58, correction: 0.66, drift: 0.15, initialDebt: 0.50, irreversibleLoss: 0.08 },
  "public-health-preparedness": { pressure: 1.30, error: 0.33, feedback: 0.64, correction: 0.66, drift: 0.14, initialDebt: 0.52, irreversibleLoss: 0.08 },
  "energy-grid": { pressure: 1.42, error: 0.30, feedback: 0.70, correction: 0.67, drift: 0.15, initialDebt: 0.62, irreversibleLoss: 0.07 },
  "sovereign-debt": { pressure: 1.38, error: 0.36, feedback: 0.60, correction: 0.65, drift: 0.14, initialDebt: 0.70, irreversibleLoss: 0.07 },
  "semiconductor-supply-chain": { pressure: 1.35, error: 0.32, feedback: 0.68, correction: 0.62, drift: 0.13, initialDebt: 0.58, irreversibleLoss: 0.06 },
  "fishery-management": { pressure: 1.60, error: 0.34, feedback: 0.65, correction: 0.50, drift: 0.08, initialDebt: 0.55, irreversibleLoss: 0.08 },
  "housing-affordability": { pressure: 1.34, error: 0.35, feedback: 0.58, correction: 0.63, drift: 0.13, initialDebt: 0.62, irreversibleLoss: 0.07 },
  "youth-mental-health": { pressure: 1.25, error: 0.30, feedback: 0.62, correction: 0.68, drift: 0.12, initialDebt: 0.52, irreversibleLoss: 0.05 },
  "pollinator-collapse": { pressure: 1.12, error: 0.26, feedback: 0.70, correction: 0.75, drift: 0.11, initialDebt: 0.35, irreversibleLoss: 0.04 },
  "education-quality": { pressure: 1.08, error: 0.24, feedback: 0.73, correction: 0.76, drift: 0.09, initialDebt: 0.30, irreversibleLoss: 0.03 },
  "healthcare-workforce": { pressure: 1.18, error: 0.28, feedback: 0.68, correction: 0.70, drift: 0.11, initialDebt: 0.38, irreversibleLoss: 0.05 },
  "aging-infrastructure": { pressure: 1.16, error: 0.25, feedback: 0.74, correction: 0.74, drift: 0.10, initialDebt: 0.34, irreversibleLoss: 0.04 },
  "water-quality": { pressure: 1.12, error: 0.24, feedback: 0.76, correction: 0.78, drift: 0.10, initialDebt: 0.30, irreversibleLoss: 0.04 },
  "geopolitical-escalation": { pressure: 1.20, error: 0.29, feedback: 0.66, correction: 0.72, drift: 0.11, initialDebt: 0.36, irreversibleLoss: 0.05 },
  "disaster-insurance": { pressure: 1.15, error: 0.26, feedback: 0.72, correction: 0.74, drift: 0.10, initialDebt: 0.34, irreversibleLoss: 0.04 },
  "data-governance": { pressure: 1.05, error: 0.23, feedback: 0.75, correction: 0.78, drift: 0.08, initialDebt: 0.28, irreversibleLoss: 0.03 },
  "llm-deployment": { pressure: 1.42, error: 0.27, feedback: 0.69, correction: 0.64, drift: 0.11, initialDebt: 0.32, irreversibleLoss: 0.05 },
  "coding-agent": { pressure: 1.58, error: 0.31, feedback: 0.65, correction: 0.57, drift: 0.13, initialDebt: 0.42, irreversibleLoss: 0.06 },
  "startup-growth": { pressure: 1.67, error: 0.34, feedback: 0.57, correction: 0.55, drift: 0.15, initialDebt: 0.48, irreversibleLoss: 0.07 },
  "hospital-throughput": { pressure: 1.54, error: 0.30, feedback: 0.62, correction: 0.56, drift: 0.13, initialDebt: 0.43, irreversibleLoss: 0.07 },
  "burnout-recovery": { pressure: 1.36, error: 0.29, feedback: 0.61, correction: 0.59, drift: 0.12, initialDebt: 0.50, irreversibleLoss: 0.06 },
  "public-transit": { pressure: 1.31, error: 0.27, feedback: 0.68, correction: 0.61, drift: 0.11, initialDebt: 0.46, irreversibleLoss: 0.05 },
  "engagement-recommender": { pressure: 1.61, error: 0.38, feedback: 0.49, correction: 0.58, drift: 0.16, initialDebt: 0.55, irreversibleLoss: 0.08 },
  "urban-reservoir": { pressure: 1.29, error: 0.24, feedback: 0.72, correction: 0.66, drift: 0.13, initialDebt: 0.47, irreversibleLoss: 0.05 },
  "emergency-response": { pressure: 1.49, error: 0.32, feedback: 0.63, correction: 0.62, drift: 0.14, initialDebt: 0.40, irreversibleLoss: 0.07 },
  "research-integrity": { pressure: 1.33, error: 0.35, feedback: 0.58, correction: 0.60, drift: 0.10, initialDebt: 0.52, irreversibleLoss: 0.06 },
};

/** Cached outputs of educational-watchlist-v2; deterministic tests recompute them. */
export const derivedDefaultWatchlist: Record<string, SimulatedWatchlistTier> = {
  "climate-biosphere": "red", "groundwater-depletion": "orange", "soil-fertility": "orange", "antimicrobial-resistance": "red", "information-integrity": "red", "institutional-trust": "red",
  "ai-agent-ecosystems": "orange", "public-health-preparedness": "orange", "energy-grid": "orange", "sovereign-debt": "orange", "semiconductor-supply-chain": "orange", "fishery-management": "orange", "housing-affordability": "orange", "youth-mental-health": "orange",
  "pollinator-collapse": "yellow", "education-quality": "yellow", "healthcare-workforce": "orange", "aging-infrastructure": "yellow", "water-quality": "yellow", "geopolitical-escalation": "orange", "disaster-insurance": "yellow", "data-governance": "yellow",
  "llm-deployment": "orange", "coding-agent": "orange", "startup-growth": "orange", "hospital-throughput": "orange", "burnout-recovery": "orange", "public-transit": "orange", "engagement-recommender": "orange", "urban-reservoir": "orange", "emergency-response": "orange", "research-integrity": "orange",
};
