import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import * as z from "zod/v4";
import {
  comparisonSpecSchema,
  empiricalEvidenceBundleSchema,
  empiricalEvidenceRegistryBundleSchema,
  empiricalEvidenceRegistryRequestSchema,
  empiricalResearchReceiptSchema,
  empiricalResearchRequestSchema,
  externalTelemetrySchema,
  experimentSpecSchema,
  interventionDefinitionSchema,
  interventionPlanDefinitionSchema,
  scenarioModuleDefinitionSchema,
  scenarioDefinitionSchema,
  scenarioProposalSchema,
  scheduledInterventionSchema,
  simulationParametersSchema,
  systemTemplateDefinitionSchema,
  sweepSpecSchema,
} from "../contracts/schemas.ts";
import { CONTRACT_VERSION } from "../contracts/constants.ts";

const outputDirectory = resolve("public/schemas/v1");
const generatedModulePath = resolve("contracts/generated-schemas.ts");
const canonicalBase = "https://viability-torus-lab.citizen-of-earth.chatgpt.site/schemas/v1";
const definitions = [
  ["simulation-parameters", "Simulation parameters", simulationParametersSchema],
  ["scheduled-intervention", "Scheduled intervention", scheduledInterventionSchema],
  ["maintenance-pattern", "Maintenance pattern", systemTemplateDefinitionSchema],
  ["system-template", "Maintenance pattern (v1 compatibility name)", systemTemplateDefinitionSchema],
  ["scenario-module", "Reusable scenario module", scenarioModuleDefinitionSchema],
  ["intervention-definition", "Reusable intervention definition", interventionDefinitionSchema],
  ["intervention-plan", "Composable intervention plan", interventionPlanDefinitionSchema],
  ["experiment", "Experiment specification", experimentSpecSchema],
  ["comparison", "Experiment comparison", comparisonSpecSchema],
  ["parameter-sweep", "Parameter sweep", sweepSpecSchema],
  ["scenario", "Scenario definition", scenarioDefinitionSchema],
  ["scenario-proposal", "Draft scenario proposal", scenarioProposalSchema],
  ["external-telemetry", "External mismatch telemetry", externalTelemetrySchema],
  ["empirical-evidence-bundle", "Browser-local empirical study evidence bundle", empiricalEvidenceBundleSchema],
  ["empirical-research-request", "Headless empirical research request", empiricalResearchRequestSchema],
  ["empirical-research-receipt", "Redacted empirical research receipt", empiricalResearchReceiptSchema],
  ["empirical-evidence-registry-request", "Evidence Registry aggregation request", empiricalEvidenceRegistryRequestSchema],
  ["empirical-evidence-registry", "Redacted Evidence Registry bundle", empiricalEvidenceRegistryBundleSchema],
] as const;

await mkdir(outputDirectory, { recursive: true });
const files: { name: string; title: string; url: string }[] = [];
const generatedSchemas: Record<string, Record<string, unknown>> = {};
for (const [name, title, schema] of definitions) {
  const jsonSchema = z.toJSONSchema(schema, { target: "draft-2020-12", unrepresentable: "any" }) as Record<string, unknown>;
  jsonSchema.$id = `${canonicalBase}/${name}.schema.json`;
  jsonSchema.title = title;
  await writeFile(resolve(outputDirectory, `${name}.schema.json`), `${JSON.stringify(jsonSchema, null, 2)}\n`, "utf8");
  generatedSchemas[`${name}.schema.json`] = jsonSchema;
  files.push({ name, title, url: `/schemas/v1/${name}.schema.json` });
}

const index = {
  schemaVersion: CONTRACT_VERSION,
  dialect: "https://json-schema.org/draft/2020-12/schema",
  schemas: files,
};
await writeFile(resolve(outputDirectory, "index.json"), `${JSON.stringify(index, null, 2)}\n`, "utf8");
await writeFile(generatedModulePath, `// Generated by scripts/generate-schemas.ts. Do not edit by hand.\nexport const GENERATED_SCHEMA_INDEX = ${JSON.stringify(index, null, 2)} as const;\nexport const GENERATED_JSON_SCHEMAS: Record<string, unknown> = ${JSON.stringify(generatedSchemas, null, 2)};\n`, "utf8");

process.stdout.write(`Generated ${definitions.length} schemas in ${outputDirectory}\n`);
